class Divisions {
  static const List<String> all = [
    'Planning / Design',
    'Site Prep',
    'Temporary Utilities',
    'Demolition',
    'Excavation and Trenching',
    'Underground Utilities',
    'Concrete',
    'Framing',
    'Exterior Doors and Windows',
    'Rough HVAC',
    'Rough Plumbing',
    'Rough Electrical',
    'Low Voltage Data Rough-In',
    'Thermal and Moisture Protection',
    'Pre-Drywall Sign-Off',
    'Drywall',
    'Drywall Dry-Out and Dehumidification',
    'HVAC Commissioning',
    'Finish Carpentry / Millwork - Phase 1',
    'Floor Coverings',
    'Finish Carpentry - Phase 2',
    'Painting',
    'Epoxy Floor Coatings',
    'Finish Electrical',
    'Finish HVAC',
    'Finish Low Voltage Data',
    'Finish Plumbing',
    'Appliances, Hardware, and Wall Specialties',
    'Shower Glass and Mirrors',
    'Final Clean',
    'Final Building Inspections',
    'Exterior Hardscape Pre-Wire and Irrigation Sleeves',
    'Exterior Flatwork',
    'Irrigation and Landscaping',
    'Exterior Electrical',
    'Exterior Structures',
    'Furnishings',
  ];
}